### ISSUE TITLE
Matrix convolution example in Haskell

### ISSUE THREAD

**Issue by rolyp** [rolyp/fluid#275]
Hi @min-nguyen, let’s use this GitHub issue to discuss what needs to be done for this activity and  capture any links to relevant documentation. I’ve renamed the repo to “fluid” (which is the working name of the programming language), so you might want to re-clone it.

As we discussed the other day with Meng, I propose we start by implementing matrix convolution in Haskell, using Haskell’s [functional arrays](https://www.haskell.org/tutorial/arrays.html) library. This will give us an idea of what we will need of our language in order to implement #272.

Some notes:
- we’ll need to avoid relying on any lazy features of Haskell, since our language is strict
- try to go minimal - what is the smallest set of operations we can get away with for the convolution example, e.g. array creation, (functional) update, indexing
- for matrix convolution itself, you might want to look at the Python [convolve](https://docs.scipy.org/doc/scipy-0.16.1/reference/generated/scipy.ndimage.filters.convolve.html) library
- the Haskell experiment can go into a new folder called `experiment` in this repo

As always, feel free to ping me if you want to discuss anything - adding comments against this issue are probably the way to go, as that will give us an audit trail of previous discussions.

Once this is done we can think about designing a syntax and semantics to add arrays to Fluid.

Subtasks:
- [x] initial experiment
- [x] default to 0 for boundary case
- [x] add at least one other strategy for boundary cases and generalise accordingly

**Comment by rolyp** [comment]
@mengwangoxf I’ve summarised what we discussed the other day in this GitHub issue - we can discuss further here if need be!

**Comment by min-nguyen** [comment]
Because arrays have dimensions defined in their type definition, I assume the resultant matrix (from convolving a filter over a 2D matrix) will need to have its dimensions dependently typed? 
For example a filter with dimensions (m, n) over an image with dimensions (i, j) using a stride length of 1 is calculated using the following, (where quot refers to the quotient).

```haskell
((quot (i - m) stride) + 1 , (quot (j - n) stride) + 1 )
```

**Comment by rolyp** [comment]
@min-nguyen It’s certainly natural to think of array types as specifying the dimensions too (just as a dependently typed vector specifies its length). However I don’t believe that’s how it works in Haskell (I’m looking at [this](https://www.haskell.org/tutorial/arrays.html) tutorial.) For example array construction has the signature

````array :: (Ix a) => (a,a) -> [(a,b)] -> Array a b```` 

Regardless of Haskell, our language is untyped, so for the implementation we’ll have to treat array dimensions as dynamic anyway. On the other hand our formalism is typed, we’d be free to use dependently typed array there if we find it helpful (again, regardless of how Haskell does things).

**Comment by rolyp** [comment]
By the way, feel free to create a branch for any code experiments.

**Comment by min-nguyen** [comment]
I've pushed a convolution function, I haven't spent too much overthinking it as I'm still quite new as to where this project is going, so I thought it'd be more practical to get your overall thoughts on things whenever you get the chance.

**Comment by min-nguyen** [comment]
I've changed convolution to use zero padding on the image, such that the resultant matrix will have the same dimensions as the original image.

**Comment by min-nguyen** [comment]
Would you suggest that I take a look at something/doing something in particular right now?
