### ISSUE TITLE
PureScript initial pass 

### ISSUE THREAD

**Issue by rolyp** [rolyp/fluid#279]
Enough of a language to get us started on a PureScript implementation where we can start experimenting with projectional slicing. As discussed today, implement the following for an initial pass supporting only natural numbers, pairs, (non-recursive) functions and lists.
- [x] types
- [x] values
- [x] contexts
- [x] environments
- [x] expressions
- [x] eliminators
- [x] pattern-matching
- [x] evaluation
- [x] an operation on natural numbers, e.g. +

**Comment by rolyp** [comment]
@min-nguyen I don’t think we’ll need the partial implementation we had of ranges, so I’ll delete that branch. If you could add the photos you took today we can use those for any discussion. I’ll be busy most of Tues, but I’ll have some time Weds if you get stuck.

**Comment by rolyp** [comment]
@min-nguyen Actually I won’t delete the branch, I’ll merge the examples as they will be useful. I’ll delete the other changes.

**Comment by rolyp** [comment]
Btw, I suggest putting the new impl in a folder called `purescript`.

**Comment by min-nguyen** [comment]
![89436051_232600094449776_71732933165056000_n](https://user-images.githubusercontent.com/22860381/76308972-c2871980-62c3-11ea-8a8a-e6ec744014c5.jpg)
![89629077_2544438455824332_4129042504513224704_n](https://user-images.githubusercontent.com/22860381/76308974-c450dd00-62c3-11ea-8505-01b1d6f1082c.jpg)
![89352574_1101718086850069_8980496927665684480_n](https://user-images.githubusercontent.com/22860381/76308978-c5820a00-62c3-11ea-8955-532626e4a21f.jpg)
![89627469_686073262227750_1613588186263453696_n](https://user-images.githubusercontent.com/22860381/76308981-c6b33700-62c3-11ea-8389-9b124166a5d5.jpg)

**Comment by min-nguyen** [comment]
I'm unsure about the best way to represent this as a data type, especially with function. Quick thoughts?

```haskell
data Typ a b = TypNum 
             | TypFunc a b 
             | TypList a 
             | TypPair a b 

data Expr = Num Int 
          | Var String
          | Pair Expr Expr 
          | Nil 
          | Cons Expr Expr
          | Let Expr Expr Expr 
          | Match Expr Elim
          | Func Elim

data Elim = VarElim Expr Expr 
          | NilElim Expr 
          | ConsElim Expr Expr 
          | PairElim Expr Expr 
```

**Comment by rolyp** [comment]
`Expr` looks good, although should the first argument to `Let` really be an `Expr`? 

For the `Elim` forms, remember that each has a _single_ expression and introduces zero or more variables.

`Typ` is actually simpler than you’re making it. Each type constructor (`TypFunc`, etc) can be thought of as an operation that given zero or more `Typ`s as arguments, produces another `Typ`. For example, `TypPair` will take a `Typ`, another `Typ`, and make a `Typ`. That should tell you how to rewrite your definition..

**Comment by min-nguyen** [comment]
You're right, it should a Var - that would mean separating Var as its own data type, or simply letting the field be a string. This is assuming we can't do things like `let (x, y) = (1, 2)`.

For Elim, am I to understand this to mean that we're matching on zero or more variables, and then branching to a single expression? As in, { Cons(x, xs) -> e }, we would treat this as matching on two variables x and xs in order to branch to e. (Sorry, this is obvious stuff, I'm overthinking about when or not I should consider something a variable or expression.)

Yeah you're right with Typ, thanks!

**Comment by rolyp** [comment]
Yes, you could introduce a `newtype` or similar for `Var`, but probably just as easy to assume string for now.

We can’t do things like `let (x, y) = ...` yet because we would want to factor such syntax through eliminators, but eliminators are too general for `let` (since they allow branching). We’ll come back to this as part of #171.

For `Elim`, exactly that, yes. A variable `x` is an expression when it’s being used, and a binder when it’s being defined.

**Comment by min-nguyen** [comment]
What types should we consider `eval` evaluate to?

**Comment by rolyp** [comment]
Good question. We’ll need to define a data type `Value`, similar to `Expr' except without `Var`, `Let` or `Match`, and with a new constructor `Closure` instead of `Func`.

**Comment by rolyp** [comment]
@min-nguyen You might find [`Data.Result`](https://pursuit.purescript.org/packages/purescript-result/0.1.0/docs/Data.Result) helpful.

**Comment by min-nguyen** [comment]
Thanks, hmm, this looks very similar to `Either`

**Comment by rolyp** [comment]
I think the difference is it’s a monad, so you can compose computations that might fail in such a way that failures propagate and the monad takes care of the plumbing for you.

**Comment by rolyp** [comment]
@min-nguyen I’m going to (slowly) start working on the parser. For the most part this won’t touch the code you’re working on. However I’ve made a couple of minor changes to the import statements in `Eval.purs` and `Lang.purs` to make some warnings go away. So you’ll need to do a `git pull` before you start a new branch.

**Comment by rolyp** [comment]
By the way, why don’t we rename `Lang.purs` to `Expr.purs`, to make the connection to the old codebase a bit more explicit?
